function [fitresult, gof] = createFit5(time, disp,disp2)
%CREATEFIT5(TIME,DISP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : time
%      Y Output: disp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Oct-2018 22:08:37


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( time, disp );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = 0.9999;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'disp vs. time', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel time
%ylabel disp
%grid on
%hold on
[fitresult2, gof2] = createFit4(time, disp2)
[xData2, yData2] = prepareCurveData( time, disp2 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = 0.9999;

% Fit model to data.
[fitresult2, gof2] = fit( xData2, yData2, ft, opts );

% Plot fit with data.
%h = plot( fitresult2, xData2, yData2 );
%legend( h, 'disp2 vs. time', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
h=plot(fitresult2);
hold on
plot(fitresult);


